version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
    groups:
      github-actions:
        patterns:
          - "*"
    cooldown:
      default-days: 7
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "14:00"
    groups:
      cargo:
        patterns:
          - "*"
  - package-ecosystem: "rust-toolchain"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "14:00"
    groups:
      rust-toolchain:
        patterns:
          - "*"
