---
# travis-ci config for pipdeptree

language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
install:
  - pip install .
  - pip install -r tests/testenv_requirements.txt
script:
  - nosetests
