__all__ = [
    "engine",
    "execute",
    "format_flags",
    "render",
    "render_with_mermaid",
    "version",
]

def engine() -> str: ...
def execute(
    args: list[str], *, color: bool = False, log_resolved: bool = True
) -> tuple[int, bytes, str, str | None]: ...
def format_flags(output_format: str, summary: bool) -> list[str]: ...
def render(args: list[str]) -> tuple[str, str, int]: ...
def render_with_mermaid(args: list[str]) -> tuple[str, str, str, int]: ...
def version() -> str: ...
