__all__ = ["engine", "execute", "render", "version"]

def engine() -> str: ...
def execute(args: list[str], *, color: bool = False, log_resolved: bool = True) -> tuple[int, bytes, str]: ...
def render(args: list[str]) -> str: ...
def version() -> str: ...
