name: Release to PyPI
on:
  push:
    tags: ["*"]
permissions:
  contents: read
jobs:
  dist:
    uses: ./.github/workflows/dist.yaml
  release:
    needs: dist
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pypi.org/project/pipdeptree/${{ github.ref_name }}
    permissions:
      id-token: write
    steps:
      - name: Download all the dists
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          merge-multiple: true
          pattern: dists-*
          path: dist/
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # v1.14.0
        with:
          attestations: true
